## template: jinja
#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

runcmd:
  - log Completed {{ds.meta_data.imds.compute.name}}-$DEV_ID.{{ds.meta_data.imds.compute.location}}.cloudapp.azure.com
