## template: jinja
#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

runcmd:
  - log_start kind
  - cd /home/{{ds.meta_data.imds.compute.osProfile.adminUsername}}
  - as_user '/usr/local/go/bin/go install sigs.k8s.io/kind@v0.12.0'
  - log_done kind
  