## template: jinja
#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

packages:
  - netbase

runcmd:
  - log_start bond_compiler
  - curl -sSL https://get.haskellstack.org/ | sh
  - as_user 'git clone https://github.com/microsoft/bond.git ~/code/Microsoft/bond'
  - as_user 'cd ~/code/Microsoft/bond; git checkout 9.0.0'
  - as_user 'cd ~/code/Microsoft/bond; stack init'
  - as_user 'cd ~/code/Microsoft/bond/compiler; stack build'
  - as_user 'cd ~/code/Microsoft/bond/compiler; stack install'
  - log_done bond_compiler
  