## template: jinja
#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

runcmd:
  - log_start cfssl
  - apt-get install golang-cfssl
  - log_done cfssl
  