[package]
name = "chiron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
mime_multipart = "0.6.0"
hyper = "0.10.16"
walkdir = "2"
base64 = "0.13.0"